@apiId = your-api-id
@region = your-region
@apiGatewayUrl = https://{{apiId}}.execute-api.{{region}}.amazonaws.com/api/v1

@usersEndpoint = {{apiGatewayUrl}}/users
@postsEndpoint = {{apiGatewayUrl}}/posts

### Get all users
GET {{usersEndpoint}}

### Get user
GET {{usersEndpoint}}/first-user

### Get all posts
GET {{postsEndpoint}}

### Get post
GET {{postsEndpoint}}/first-post
